### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by ElectroBoy404NotFound** [ringwormGO-organization/DiscordBot-v2#3]
A personal task list for this repo:

Bot:
  - [ ] Use embeds instead of text message
  - [x] Use .env files instead of hardcodded token (#1)
  - [x] Use slash commands (#1)
  - [ ] Code cleanup & Documentation
 
Commands:
  - [x] Ban command (#1)
  - [x] Kick command (#2)
  - [x] Ping command (#1)
  - [ ] Help command
  - [ ] Timeout/Mute command
  - [ ] About command
  - [ ] Github command
 
Misc:
  - [ ] Auto roles
  - [ ] Auto Nicknames
  - [ ] Server issue tickets
